sudo: required
language: generic
services:
- docker
env:
  matrix:
  - ver=0.4.0
  global:
  # DOCKER_USERNAME
  - secure: q5Qxlybe/s+U0Zq1E+CHlIqlpgn8MFCc1zI2cT9EB6wwBQo4R1m46tsi120CiTblcQWA54FveB5FL0U218dUL8fSNl7Ox6tSb52A9+dWJt+GVyJOBuU0mYbI5ezaTYy6kl1yNqI26gi2Fq/NVNN4igSOx2/j054gaT2s4kU1mhqEYGOI8thvSgQ6PTiF9wqTQQ5+iUY1KAheH/RbDBWkpmtPUc9hrd6Y7CZSQlo5dQndXfl0Oe79ulU+1GWFyheCrdrLSAPPTHSuRX89/Zpfqv2sF30UrdJa2287as/cjmGbcpjyVjG/zISxava2nM/nVcoixiAZzM9Z8o05TLOqcYDhS8ot+flnlp9OH4zLI5AwukocG5R6H2nq1XMYJ9ofMPEtwrz1XxXMnJfiQVjYupoNOtgZTo+oJY302rr/+1dM61OBCFiH2bMjuYZuGNQwtRko6TBoSaBl5aovyNlBGBQtGZ9VAGhOqIgg8XGOE4pgI6fOOwxIhgxjCgJUPV6xn396wlz6cOWni64O5phxUDTMUV45n2iROZHiljB5GoXEYFsHmh3Umx3QaSswSIJ0AJ2lc8ysbN44R6S6knuCBDIO+QZGWIUqQrO2lBcQ7ZCcsbPt06UmLO1TbI/ReXwvK2kg9hScBXqaxRxqcuW/prGn9DUP/+nRrMvrcagXqlg=
  # DOCKER_PASSWORD
  - secure: SUPGP0kS4wi0kc0EAJ2h++JKHL7GFJr9gdaqCUAOlVIgrOVqxARwFVtKzbyqDOHTGVfRSQMugM1ZbxBXvrTk4Y2GMELXBcNnZPG0BqYJb/lTL2dLsdgsif2Ze8rEpp0zqwnieDiA6IsdpYmR4qyhfFkmSbH0v0A6VXIi3iM8SmvfPcaejoMF/6SS71Oa1GQOnG1ywrzamssXRzW+EIVLDWbjKH9XAhQTc9Nan1cCNQLJakDZL8sIeHYfujSNwvIVVB19DWU18NfxmokB7ddCT/vCobNuM7K69lvMBJGx8yM1LoTM3bjHn3PIp6nPWvSVnobGCFzPkiZSjXOdqDxG4RGH9QJQqQGKqc0HPIOfdUw+xKKaA1WD9QPQU3vlP6TUGxpGOYbRl5WvGfgQK/0l62q6V+oss4ebhXjdoGxkrG2sSpgWMJsZUnjgyuncFKD2bsKML8qnpQcf1Eg9B/+ZETh8oJCYSA2GeTv1B85JbA04RPFa9kdBjey6+8Bc9Cd1HcIZfhSreowHocbod/DqajC1lGqBwAFupAd3HJjBYygf3a8ts7T8xk8HKM72UMqtDYtEJVVTZG+cB4JarH7DQmxXZkfbI551G8Xl/TKhSi/lrOapX0gqkOuPvLY2XFcpZWn0KgV40YW4r+tFaLXB1bPNB8TaMFXxVXovEq68pjQ=
script:
- make build
- make test
deploy:
- provider: script
  script: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && make deploy
  on:
    branch: master
